version: '3.9'
services:
  api:
    env_file:
      - ./api/.env
    build:
      context: ./api
      dockerfile: Dockerfile

    ports:
      - "3000:3000"

  app:
    build:
      context: ./app
      dockerfile: Dockerfile

    ports:
      - "4000:80"